services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: backend-container
        environment:
            PORT: 5000
            SECRET_KEY: expense-tracker-secret
            MONGO_URL: mongodb://mongo:27017/expense-tracker

            F_API_KEY: AIzaSyAVZgcJdJUn8rnCRCpQUHRpVQk85kMWbuc
            F_AUTH_DOMAIN: reactapp-2edc4.firebaseapp.com
            F_DATABASE_URL: https://reactapp-2edc4-default-rtdb.asia-southeast1.firebasedatabase.app
            F_PROJECT_ID: reactapp-2edc4
            F_STORAGE_BUCKET: reactapp-2edc4.appspot.com
            F_MESSAGING_SENDER_ID: 50432815711
            F_APP_ID: 1:50432815711:web:ea8861e7659d1947f321ea
        ports:
            - "5000:5000"
        depends_on:
            - mongo

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: frontend-container
        environment:
            VITE_REACT_API_URL: http://localhost:5000
        ports:
            - "8080:8080"
        depends_on:
            - server
